require 'tmpdir'

RSpec.describe JsonSchemasToTypescript do
  describe '.generate_types_files' do
    subject(:generate_types_files) do
      described_class.send(:generate_types_files, schema_paths)
    end

    let(:schema_paths) { %w[first_schema.json second_schema.json] }
    let(:first_types_path) { 'FirstSchema.ts' }
    let(:second_types_path) { 'SecondSchema.ts' }

    before do
      allow(described_class).to receive(:types_path).and_return(
        first_types_path,
        second_types_path,
      )
    end

    it 'generates every TypeScript file in one Node process' do
      allow(described_class).to receive(:system).with(
        'node',
        Rails.root.join('tools/json_schemas_to_typescript.mjs').to_s,
        schema_paths.first,
        first_types_path,
        schema_paths.second,
        second_types_path,
        exception: true,
      )

      generate_types_files

      expect(described_class).to have_received(:system).once.with(
        'node',
        Rails.root.join('tools/json_schemas_to_typescript.mjs').to_s,
        schema_paths.first,
        first_types_path,
        schema_paths.second,
        second_types_path,
        exception: true,
      )
    end

    context 'when there are no schemas to generate' do
      let(:schema_paths) { [] }

      it 'does not start a Node process' do
        allow(described_class).to receive(:system)

        generate_types_files

        expect(described_class).not_to have_received(:system)
      end
    end
  end

  describe '.format_types_file' do
    it 'restores the top-level array omitted by Quicktype' do
      Dir.mktmpdir('json-schemas-to-typescript-spec') do |directory|
        schema_path = File.join(directory, 'array_schema.json')
        types_path = File.join(directory, 'ArrayResponse.ts')

        File.write(schema_path, JSON.generate(type: 'array'))
        File.write(types_path, <<~TYPESCRIPT)
          export interface ArrayResponse {
              created_at: Date;
          }
        TYPESCRIPT
        allow(described_class).to receive(:types_path).with(schema_path).and_return(types_path)

        described_class.send(:format_types_file, schema_path)

        expect(File.read(types_path)).to eq(<<~TYPESCRIPT)
          export type ArrayResponse = Array<ArrayResponseElement>

          // This file was generated by quicktype. Do not edit this file directly.

          interface ArrayResponseElement {
              created_at: string;
          }
        TYPESCRIPT
      end
    end
  end
end
