---
version: 2
updates:
  - package-ecosystem: bundler
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:04'
      timezone: America/Chicago
    allow:
      - dependency-type: all
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:04'
      timezone: America/Chicago
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: 'daily'
      time: '04:04'
      timezone: America/Chicago
