version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: weekly
    time: "03:52"
    timezone: America/Chicago
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: codecov
    versions:
    - 0.5.1
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: weekly
    time: "03:52"
    timezone: America/Chicago
  open-pull-requests-limit: 20
  ignore:
  - dependency-name: chart.js
    versions:
    - 3.0.2
    - 3.1.0
    - 3.1.1
    - 3.2.0
  - dependency-name: mini-css-extract-plugin
    versions:
    - 1.3.5
    - 1.3.6
    - 1.3.7
    - 1.3.8
    - 1.3.9
    - 1.4.0
    - 1.4.1
    - 1.5.0
  - dependency-name: "@babel/preset-env"
    versions:
    - 7.13.15
  - dependency-name: vue-router
    versions:
    - 4.0.6
  - dependency-name: postcss
    versions:
    - 8.2.6
    - 8.2.7
  - dependency-name: caniuse-lite
    versions:
    - 1.0.30001181
