# do not check ActionMailbox/ActiveStorage models, since they are provided by Rails
ActionMailbox::InboundEmail:
  enabled: false
ActiveAdmin::Comment:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
JsonPreference:
  json:
    NullConstraintChecker:
      enabled: false # We don't want to require presence, just not nil.
LogEntry:
  enabled: false
