# do not check ActionMailbox/ActiveStorage models, since they are provided by Rails
ActionMailbox::InboundEmail:
  enabled: false
ActiveStorage::Blob:
  enabled: false
ActiveStorage::VariantRecord:
  enabled: false
ActiveStorage::Attachment:
  enabled: false
