---
detectors:
  TooManyStatements:
    enabled: true
    exclude:
    - initialize
    max_statements: 6 # default is 5
directories:
  "app/controllers":
    # Using instance variable in controllers is a pretty essential Rails pattern
    InstanceVariableAssumption:
      enabled: false
    # The purpose of a controller class should be pretty obvious
    IrresponsibleModule:
      enabled: false
    # Sometimes it makes sense to check for `nil`...
    NilCheck:
      enabled: false
  "app/workers":
    # Sidekiq workers sometimes need to set an instance variable in #perform rather than #initialize
    InstanceVariableAssumption:
      enabled: false
