AllCops:
  EnabledByDefault: true
  TargetRubyVersion: 2.4
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/IndentArray:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/RescueWithoutErrorClass:
  Enabled: false
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Rails:
  Enabled: true
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - describe
    - head
    - puts
    - render
    - require
Style/MissingElse:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInLiteral:
  EnforcedStyleForMultiline: comma
