require: rubocop-performance
AllCops:
  EnabledByDefault: true
  Exclude:
    - 'db/schema.rb'
  TargetRubyVersion: 2.4
Bundler/GemComment:
  Enabled: false
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/ClassStructure:
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  Max: 100
Metrics/MethodLength:
  Max: 20
Rails:
  Enabled: true
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - add_foreign_key
    - add_column
    - add_index
    - change_column_null
    - datetime
    - desc
    - describe
    - drop_table
    - gem
    - fail
    - file
    - float
    - head
    - include
    - integer
    - jsonb
    - not_to
    - p
    - print
    - puts
    - references
    - render
    - require
    - require_relative
    - ruby
    - string
    - source
    - to
Style/MissingElse:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
