inherit_gem:
  runger_style:
    - rulesets/default.yml
    - rulesets/performance.yml
    - rulesets/rails.yml

require:
  - ./tools/custom_cops/require_all_custom_cops.rb

AllCops:
  Exclude:
    - !ruby/regexp /db\/migrate\/(201|202[0-4])/
  StringLiteralsFrozenByDefault: true
  SuggestExtensions: false

CustomCops/DontRollBackDatamigration:
  Include:
    - db/datamigrate/**/*.rb
CustomCops/DontIncludeSidekiqWorker:
  Include:
    - app/workers/**/*.rb
Style/ClassAndModuleChildren:
  Exclude:
    - 'tools/custom_cops/**/*.rb'
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
