inherit_gem:
  runger_style:
    - default.yml

require:
  - rubocop-rails
  - ./tools/custom_cops/dont_include_sidekiq_worker.rb
Rails:
  Enabled: true
Rails/Output:
  Enabled: false
Rails/RakeEnvironment:
  Enabled: false
