inherit_gem:
  runger_style:
    - rulesets/capybara.yml
    - rulesets/default.yml
    - rulesets/performance.yml
    - rulesets/rails.yml
    - rulesets/rspec.yml

require:
  - ./tools/custom_cops/dont_include_sidekiq_worker.rb
