require:
  - rubocop-performance
  - rubocop-rails
AllCops:
  EnabledByDefault: true
  Exclude:
    - !ruby/regexp /\/db\/migrate/201[1-8].*\.rb\z/
    - db/schema.rb
    - lib/tasks/auto_annotate_models.rake
  TargetRubyVersion: 2.4
Bundler/GemComment:
  Enabled: false
Layout/AlignArguments:
  EnforcedStyle: with_fixed_indentation
Layout/ClassStructure:
  ExpectedOrder:
      - module_inclusion
      - constants
      - public_class_methods
      - initializer
      - public_methods
      - protected_methods
      - private_methods
Layout/DotPosition:
  EnforcedStyle: trailing
Layout/IndentFirstArrayElement:
  EnforcedStyle: consistent
Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented
Layout/SpaceBeforeBlockBraces:
  Enabled: false
Layout/SpaceBeforeSemicolon:
  Enabled: false
Layout/SpaceInsideHashLiteralBraces:
  EnforcedStyle: no_space
Lint/UnneededSplatExpansion:
  Enabled: false
Metrics/AbcSize:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Metrics/LineLength:
  IgnoredPatterns:
    # ignore line length if the line is a comment without any spaces; it's probably not something we
    # can fix (e.g. a long file path)
    - !ruby/regexp /^ *#? [\S]+$/
  Max: 100
Metrics/MethodLength:
  Max: 30
Naming/RescuedExceptionsVariableName:
  Enabled: false
Rails:
  Enabled: true
Rails/Output:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Style/ClassAndModuleChildren:
  EnforcedStyle: compact
Style/Copyright:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/DocumentationMethod:
  Enabled: false
Style/EmptyCaseCondition:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: true
Style/GlobalVars:
  Enabled: false
Style/GuardClause:
  Enabled: false
Style/IfUnlessModifier:
  Enabled: false
Style/InlineComment:
  Enabled: false
Style/Lambda:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - add_foreign_key
    - add_column
    - add_index
    - change
    - change_column_null
    - create_table
    - datetime
    - desc
    - describe
    - drop_table
    - gem
    - fail
    - file
    - float
    - head
    - include
    - integer
    - jsonb
    - load
    - not_to
    - p
    - print
    - puts
    - references
    - remove_column
    - render
    - require
    - require_relative
    - ruby
    - run
    - string
    - source
    - text
    - timestamp
    - to
Style/MissingElse:
  Enabled: false
Style/NegatedIf:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Style/RescueStandardError:
  Enabled: false
Style/ReturnNil:
  Enabled: false
Style/Semicolon:
  Enabled: false
Style/SignalException:
  Enabled: false
Style/StderrPuts:
  Enabled: false
Style/StringHashKeys:
  Enabled: false
Style/TernaryParentheses:
  Enabled: false
Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: comma
Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: comma
