inherit_gem:
  runger_style:
    - rulesets/capybara.yml
    - rulesets/default.yml
    - rulesets/factory_bot.yml
    - rulesets/performance.yml
    - rulesets/rails.yml
    - rulesets/rspec.yml

require:
  - ./tools/custom_cops/dont_include_sidekiq_worker.rb

AllCops:
  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '').sub(/\/$/, '/**/*').rstrip %>
  <% end %>

# Temporarily disable this cop because we are getting false positives with prism.
Layout/HeredocIndentation:
  Enabled: false
