inherit_gem:
  runger_style:
    - rulesets/capybara.yml
    - rulesets/default.yml
    - rulesets/factory_bot.yml
    - rulesets/performance.yml
    - rulesets/rails.yml
    - rulesets/rspec_rails.yml
    - rulesets/rspec.yml

require:
  - ./tools/custom_cops/require_all_custom_cops.rb

AllCops:
  Exclude:
  <% `git status --ignored --porcelain`.lines.grep(/^!! /).each do |path| %>
    - <%= path.sub(/^!! /, '').sub(/\/$/, '/**/*').rstrip %>
  <% end %>
  StringLiteralsFrozenByDefault: true

CustomCops/DontRollBackDatamigration:
  Include:
    - db/datamigrate/**/*.rb
CustomCops/DontIncludeSidekiqWorker:
  Include:
    - app/workers/**/*.rb
Style/ClassAndModuleChildren:
  Exclude:
    - 'tools/custom_cops/**/*.rb'
Style/FrozenStringLiteralComment:
  EnforcedStyle: never
