expected-num-github-checks: 4
javascript-watch-command: bin/vite dev
spec-commands: |
  export RAILS_ENV=test PALLETS_CONCURRENCY=${PALLETS_CONCURRENCY:-6} DISABLE_SPRING=1
  export POSTGRES_USER=david_runger POSTGRES_HOST=localhost
  set -x
  redis-cli -n 10 FLUSHDB
  bin/run-tests
