language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - "2.5.1"
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - RAILS_ENV=test NODE_ENV=test SECRET_KEY_BASE=0af8c0e49e9259f2d777cfcd121d8540cee914c34b0abf08dd825bdee47c402daf9f2b9b74a9fff6f88ed95257ae39504e0d59c66400413b0cf7d29079c6358b
before_install:
  - gem install bundler
  - . $HOME/.nvm/nvm.sh
  - nvm install 10.0.0
  - nvm use 10.0.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - "[ \"$(ruby --version | cut -c1-11)\" == 'ruby 2.5.1p' ]"
  - "[ \"$(bundle --version)\" == 'Bundler version 1.16.2' ]"
  - "[ \"$(node --version)\" == 'v10.0.0' ]"
  - "[ \"$(yarn --version)\" == '1.6.0' ]"
  - yarn install
  - bundle exec rails db:create
  - bundle exec rails db:schema:load
  - bundle exec rails spec:fixture_builder:rebuild
  - bundle exec rails spec:rb
  - bundle exec rails spec:js
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: OgKrlYneYR/TZHiiQliqC6SVBbkLdvyQmxtAJRfCv3ae1DvMMAfBsVs+ByCpTyuSwregOLk6/jCihzmxg7dvn2PyWvbZYGhzdXQzfhvGiy9gj57SVwx399YTlAU7dcp2GC5YHbky++TOXbSHaqXP5BfBkgvtrnKrUWEeYM6CS2w4sP/ibD5TK7CJ3FDozp1OCl1Bi62+Dv3OubKj9qDEEKHbO+cZHnMq9wEYslRdnZTD7no3IRYu0K8tdVAXUTB1/DYpY419qARWgrKheAgR7QyRMjOteNXghspnuMmkMjv6/XbiR6kJ9yPUwB7oiPK/kfu9Gc4kj9fytpyLFyHFXF1gvk43eXA4xNQ4aLfAVAwrrvDlgs+NeL5BlaRSZm6KUG5vEkss591MBvG5xgw5ocPUgxsDpFXoD+3sP/NRf8QCThgBszOsC4b3afTSqETytq16qb0Tr5BhGQey8nGlKcrhXNiqknSEPlSSBWWcXnkOKRAdkD9BE0G6Bniuk5vuL7B1RGzh+JiAwlPRmUopGfGO5+Nge2vhzik3fU83c+4JZTydXdwItTWLimyveb0WHqzWINjUt0i7zvtHzcQ+MQN53ANSr0WmgTGWR31nHrqZJMqb+qfzb+jxX9BT2A2g2yWy6pi02+24mv8zzBFdx1HgqK54hj1qSH3yvCB/ObA=
  strategy: git
  app: davidrunger
