language: ruby
cache:
  directories:
    - $HOME/.rvm/gems/ruby-2.4.1/gems/
    - node_modules
rvm:
  - "2.4.2"
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  - RAILS_ENV=test NODE_ENV=test SECRET_KEY_BASE=0af8c0e49e9259f2d777cfcd121d8540cee914c34b0abf08dd825bdee47c402daf9f2b9b74a9fff6f88ed95257ae39504e0d59c66400413b0cf7d29079c6358b
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v8.7.0
  - nvm use v8.7.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - bundle install
  - yarn install
script:
  - bin/rake db:create
  - bin/rake db:schema:load
  - bin/rake spec:fixture_builder:rebuild
  - bin/rake spec:rb
  - bin/rake spec:js
notifications:
  email:
    on_success: never
    on_success: never
deploy:
  provider: heroku
  api_key:
    secure: faDkASJEzEkL1CAwxxBmjOX7/qIrE4ueNeA2tZSnqIzKhP6+YOioOHJMPZZ43dYwVUxyWe+GeUquMkImLGjl2uV8e+qZJz25tda2gckB+CGzmgDfXQ00kJVzUTCmHf9J6ZeZ1XIKYVUe3E3mDVIogplIukG+ubj+FqfNkBV4LZ5RWEKaeYfcaM8veZqsnkqHkz0H7FXPruDUyrZGpc06+EQQdKkUlLypOssxjXGbhIcJzR99hpdD1u26Jow2kRINjdqCSPi3lf5xKeSQVElOcFuIdkHutbdprwUNhqKryDO7YM95O4WWPlYQ9gJ7QgUAZStsFy2pSRQSHtV2PVLH4k5gdPwgHtr+74MnJWSdBdPtmBPRmjkRWkHrmj2lXlsl0dktWWK6NiXWSzkKTx56kgc/zC2RABu3qKHdK2k9iVYndHPz0sJsN2LAj5SCqV2KGJdNEUaAQGkdoAktmhqxaqvgsTegOyPXV3QAIOBey1V95ubzn99LIkqqTRWRlglbqvXAsf5wVVmoxQ6kLT+lsbpJrWQW33FhGkPcciDllWeTbmeLLE1xIHI0puneYBEXrv5ZLdgXUuA11emQ+YIflb6/h6m8Ze6K+jql5Y1FAwHt/eaPA9eXSMhZh0cfEQBdoYvfKJGmTK0GIrtGQpGJVS1k7GnH4szZK2jszjuKgs0=
  strategy: git
  app: davidrunger
  run:
    - "bin/rake db:migrate"
    - restart
