language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - "2.6.5"
services:
  - postgresql
  - redis-server
addons:
  chrome: stable
  postgresql: "9.6"
env:
  - RAILS_ENV=test NODE_ENV=test SECRET_KEY_BASE=0af8c0e49e9259f2d777cfcd121d8540cee914c34b0abf08dd825bdee47c402daf9f2b9b74a9fff6f88ed95257ae39504e0d59c66400413b0cf7d29079c6358b
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 12.13.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.15.2
  - export PATH="$HOME/.yarn/bin:$PATH"
  # To get a different version of chromedriver, see http://chromedriver.chromium.org/downloads
  - CHROMEDRIVER_VERSION=$(wget -qO- https://chromedriver.storage.googleapis.com/LATEST_RELEASE)
  - curl -o tmp/chromedriver.zip https://chromedriver.storage.googleapis.com/$CHROMEDRIVER_VERSION/chromedriver_linux64.zip
  - unzip -d "$HOME/bin/" tmp/chromedriver.zip
script:
  - ruby --version && [ "$(ruby --version | cut -c1-11)" == 'ruby 2.6.5p' ]
  - bundle --version && [ "$(bundle --version)" == 'Bundler version 1.17.3' ]
  - node --version && [ "$(node --version)" == 'v12.13.0' ]
  - yarn --version && [ "$(yarn --version)" == '1.15.2' ]
  - chromedriver --version # print chromedriver version, but don't check it, because it changes
  - yarn install
  - bin/rails spec:setup_js > /dev/null 2>&1 &
  - bundle exec rubocop $(git ls-tree -r HEAD --name-only) --force-exclusion --format clang
  - ./node_modules/.bin/stylelint app/**/*.{css,scss,vue} --max-warnings 0
  - bin/rails db:create
  - bin/rails db:schema:load
  - bin/rails spec:fixture_builder:rebuild
  - bin/rails spec:poll_js
  - ./node_modules/.bin/eslint --max-warnings 0 --ext .js,.vue app/javascript/ spec/javascript/
  - bin/rails spec:run_js
  - bin/rails spec:rb
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  # This token will expire 2020-02-15.
  # To make a new one, see: https://docs.travis-ci.com/user/deployment/heroku/
  api_key:
    secure: iONIuLBs6xs40wbvwtxgoBwskP/r8sGeELkLGX12fXITNL7biYqgM2xf/onNqopMONw1DSY6KrtIQBGi2kcr1fOcVloKyZUEYvjpCgqqfuEGC+gQf4HBtOURzmtgabkxECIo6Iw488+ONi65VzbnmExnToSq0wIdoObrhjl/8jeYqB+MQHlRRqz0AuYixHesKAy6f60LJEkW8nAiQnPYaOZxkM23l55DUjjIqljIUGSjFnEBYFwyr9YrOO8bibxgZKiDZC0M1hxtoWInnPbOkSesW4yOL46Nh8tQ76EYwI+8sdxyTP9wxKJC82IUtJ5RiCHLxCjwckjKuJGJklehGxSMF81KLAeCDfvnjC9jeD6ufguaoi1bVobZZ/0wtjR70m36p+WLFmCPjxCZYq0AQoY+K9aYjQ77ep3Ifj4pz2InUprQWnAGIVOSSN4HN2213EQJEi74f2jtMdMRxGcYyLDj03vjf3gUIbyCRjoiLZrYGna0/klwnYZgHyWF26OwEfoKSfMvaiDFQUMnrY2STw80WQQoY1lfj9zESyWgUuSnce7jMI5eHvNxK1cfYs/qdvpVif4wqOKLQt3G9Gos0SLahC+3wXZK/pL8FwzGzhlK7hZL5bvBRk4h0nPR8s5t+Sdsez+w5u0ufE2MzjA7N5iTNSBuxI9nL41XBgXNfW8=
  strategy: git
  app: davidrunger
