language: ruby
sudo: false
cache:
  bundler: true
  directories:
    - node_modules
rvm:
  - "2.4.2"
services:
  - postgresql
addons:
  postgresql: "9.6"
env:
  - RAILS_ENV=test NODE_ENV=test SECRET_KEY_BASE=0af8c0e49e9259f2d777cfcd121d8540cee914c34b0abf08dd825bdee47c402daf9f2b9b74a9fff6f88ed95257ae39504e0d59c66400413b0cf7d29079c6358b
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install 8.9.3
  - nvm use 8.9.3
  - export PATH="$HOME/.yarn/bin:$PATH"
script:
  - "[ \"$(node --version)\" == 'v8.9.3' ]"
  - "[ \"$(yarn --version)\" == '1.3.2' ]"
  - yarn install
  - bin/rails db:create
  - bin/rails db:schema:load
  - bin/rails spec:fixture_builder:rebuild
  - bin/rails spec:rb
  - bin/rails spec:js
notifications:
  email:
    on_success: never
    on_failure: always
deploy:
  provider: heroku
  api_key:
    secure: OgKrlYneYR/TZHiiQliqC6SVBbkLdvyQmxtAJRfCv3ae1DvMMAfBsVs+ByCpTyuSwregOLk6/jCihzmxg7dvn2PyWvbZYGhzdXQzfhvGiy9gj57SVwx399YTlAU7dcp2GC5YHbky++TOXbSHaqXP5BfBkgvtrnKrUWEeYM6CS2w4sP/ibD5TK7CJ3FDozp1OCl1Bi62+Dv3OubKj9qDEEKHbO+cZHnMq9wEYslRdnZTD7no3IRYu0K8tdVAXUTB1/DYpY419qARWgrKheAgR7QyRMjOteNXghspnuMmkMjv6/XbiR6kJ9yPUwB7oiPK/kfu9Gc4kj9fytpyLFyHFXF1gvk43eXA4xNQ4aLfAVAwrrvDlgs+NeL5BlaRSZm6KUG5vEkss591MBvG5xgw5ocPUgxsDpFXoD+3sP/NRf8QCThgBszOsC4b3afTSqETytq16qb0Tr5BhGQey8nGlKcrhXNiqknSEPlSSBWWcXnkOKRAdkD9BE0G6Bniuk5vuL7B1RGzh+JiAwlPRmUopGfGO5+Nge2vhzik3fU83c+4JZTydXdwItTWLimyveb0WHqzWINjUt0i7zvtHzcQ+MQN53ANSr0WmgTGWR31nHrqZJMqb+qfzb+jxX9BT2A2g2yWy6pi02+24mv8zzBFdx1HgqK54hj1qSH3yvCB/ObA=
  strategy: git
  app: davidrunger
  run:
    - "bin/rails db:migrate"
    - restart
