language: ruby
cache: bundler
rvm:
  - "2.4.1"
services:
  - postgresql
addons:
  postgresql: "9.4"
env:
  - RAILS_ENV=test NODE_ENV=test SECRET_KEY_BASE=0af8c0e49e9259f2d777cfcd121d8540cee914c34b0abf08dd825bdee47c402daf9f2b9b74a9fff6f88ed95257ae39504e0d59c66400413b0cf7d29079c6358b
before_install:
  - . $HOME/.nvm/nvm.sh
  - nvm install v8.7.0
  - nvm use v8.7.0
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.2.1
  - export PATH="$HOME/.yarn/bin:$PATH"
install:
  - bundle install
  - yarn install
script:
  - bin/rake db:create
  - bin/rake db:schema:load
  - bin/rake spec:fixture_builder:rebuild
  - bin/rake spec:rb
  - bin/rake spec:js
notifications:
  email:
    on_success: never
    on_success: never
