---
version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
    ports:
      - "127.0.0.1:5432:5432"
    environment:
      POSTGRES_USER: david_runger
      POSTGRES_HOST_AUTH_METHOD: trust

volumes:
  postgresql:
