x-rails-config: &default-rails-config
  build:
    context: .
  depends_on:
    initialize_database:
      condition: service_completed_successfully
  env_file:
    # NOTE: We need this to have DATABASE_URL in bin/docker-entrypoint.
    - .env.production.local
  logging:
    driver: syslog
    options:
      # NOTE: The syslog-address value will be built into the image.
      syslog-address: ${PAPERTRAIL_URL:-setpapertrailurl://it-was-not-set}
      tag: '{{.Name}}/{{.ID}}'
  networks:
    - external
    - internal

x-redis-config: &redis
  healthcheck:
    test: ['CMD', 'redis-cli', 'ping']
    start_period: 20s
    start_interval: 1s
    interval: 10s
    timeout: 1s
    retries: 1
  image: redis:7.2.5-alpine
  networks:
    - internal

services:
  certbot:
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    image: certbot/certbot
    networks:
      - external
    volumes:
      - ./ssl-data/certbot/conf:/etc/letsencrypt
      - ./ssl-data/certbot/www:/var/www/_letsencrypt
  clock:
    <<: *default-rails-config
    command: ['bin/skedjewel']
    healthcheck:
      test: ps -eo cmd | grep -P '^[b]in/skedjewel$'
      start_period: 10s
      start_interval: 1s
      interval: 10s
      timeout: 1s
      retries: 1
  initialize_database:
    <<: *default-rails-config
    depends_on:
      postgres:
        condition: service_healthy
      redis-app:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
  nginx:
    command: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & nginx -g "daemon off;"'''
    healthcheck:
      test: curl --fail http://localhost/
      start_period: 20s
      start_interval: 1s
      interval: 60s
      timeout: 1s
      retries: 1
    image: nginx:1.27.0-alpine
    networks:
      - external
      - internal
    ports:
      - 80:80
      - 443:443
    profiles:
      - nondefault
    volumes:
      - ./config/nginx/:/etc/nginx/:ro
      - ./ssl-data/certbot/conf:/etc/letsencrypt
      - ./ssl-data/certbot/www:/var/www/_letsencrypt
      - app-public:/var/www/david-runger-public:ro
  postgres:
    env_file:
      - .env.postgres.local
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'david_runger']
      start_period: 20s
      start_interval: 1s
      interval: 10s
      timeout: 1s
      retries: 1
    image: postgres:16.3-alpine
    networks:
      - internal
    volumes:
      - postgresql:/var/lib/postgresql/data
    environment:
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      POSTGRES_USER: david_runger
  redis-app:
    <<: *redis
    # https://stackoverflow.com/a/72593084/4009384
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD is required}"
    env_file:
      - .env.redis-app.local
    volumes:
      - redis:/data
  redis-cache:
    <<: *redis
    # https://stackoverflow.com/a/72593084/4009384
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server /usr/local/etc/redis/redis.conf --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD is required}"
    env_file:
      - .env.redis-cache.local
    volumes:
      - ./redis/redis-cache.conf:/usr/local/etc/redis/redis.conf
  s3_db_backup:
    env_file:
      - .env.s3_db_backup.local
    image: dokku/s3backup
    networks:
      - external
    profiles:
      - nondefault
  web:
    <<: *default-rails-config
    command: ['bin/rails', 'server', '--binding', '0.0.0.0']
    expose:
      - '3000'
    healthcheck:
      test: curl --silent --output /dev/null --fail localhost:3000/up
      start_period: 30s
      start_interval: 1s
      interval: 10s
      timeout: 1s
      retries: 1
    profiles:
      - nondefault
    volumes:
      - ./blog:/app/blog
  worker:
    <<: *default-rails-config
    command: ['bin/sidekiq']
    healthcheck:
      test: REDIS_URL="$$REDIS_URL/1" bin/sidekiqmon | grep --quiet "$$(hostname)"
      start_period: 30s
      start_interval: 5s
      interval: 60s
      timeout: 5s
      retries: 1

networks:
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  app-public:
  postgresql:
  redis:
