x-logging-config: &default-logging
  driver: 'json-file'
  options:
    max-size: '100m'
    max-file: '5'
    compress: 'true'

x-rails-config: &default-rails-config
  build:
    args:
      - GIT_REV=${GIT_REV:-}
      - RAILS_ENV=${RAILS_ENV:-}
      - RUBY_VERSION=${RUBY_VERSION:-}
      - CONTENT_SIGNING_PUBLIC_KEY=${CONTENT_SIGNING_PUBLIC_KEY:-}
    context: .
  depends_on:
    initialize_database:
      condition: service_completed_successfully
  develop:
    watch:
      - action: sync
        path: .
        target: /app
  env_file:
    # NOTE: We need this to have DATABASE_URL in bin/docker-entrypoint.
    - .env.production.local
  environment:
    # CAUTION: `web` overrides all env vars listed here with its own `environment` section.
    RAILS_MAX_THREADS: 1
  logging: *default-logging
  networks:
    - external
    - internal

x-redis-config: &redis
  depends_on:
    redis-overcommit:
      condition: service_started
    vector:
      condition: service_started
  healthcheck:
    test: ['CMD', 'redis-cli', 'ping']
    start_period: 20s
    start_interval: 1s
    interval: 5m
    timeout: 1s
    retries: 1
  image: redis:8.4.0-alpine@sha256:4eec4565e45aa0b3966554c866bc73211e281b0b3d89fe9a33c982e6faca809d
  logging: *default-logging
  networks:
    - internal

services:
  cadvisor:
    command:
      # Add options to lower CPU/memory use. https://github.com/google/cadvisor/issues/ 2523
      - '--docker_only'
      - '--docker=tcp://docker-socket-proxy:2375'
      - '--housekeeping_interval=30s'
      - '--enable_metrics'
      - 'cpu,diskIO,memory,network'
    cpu_shares: 512
    depends_on:
      docker-socket-proxy:
        condition: service_healthy
    expose:
      - '8080'
    image: ghcr.io/google/cadvisor:v0.60.5@sha256:763aecf1c32c2be8a1a75f9abfc2fc461005c9dbbaa39cb356b354aac1296dbe
    networks:
      - docker-socket-proxy
      - internal
    volumes:
      - /sys:/sys:ro # Seems to be needed for CPU and Disk I/O usage.
      - /var/lib/docker/:/var/lib/docker:ro # Seems to be needed for memory usage.
  certbot:
    cpu_shares: 256
    depends_on:
      vector:
        condition: service_started
    entrypoint: "/bin/sh -c 'trap exit TERM; while :; do certbot renew; sleep 12h & wait $${!}; done;'"
    healthcheck:
      test: certbot --version
      start_period: 30s
      start_interval: 5s
      interval: 1h
      timeout: 10s
      retries: 1
    image: certbot/certbot:v3.2.0@sha256:3ad1eb352f6b2ae3f359dce4b262f699cc178be0ab9d9f375210e8741404720e
    logging: *default-logging
    networks:
      - external
    volumes:
      - ./ssl-data/certbot/conf:/etc/letsencrypt
      - ./ssl-data/certbot/www:/var/www/_letsencrypt
  clock:
    <<: *default-rails-config
    command: ['bin/skedjewel']
    cpu_shares: 1024
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 6M
    healthcheck:
      test: ps -eo cmd | grep -P '^[b]in/skedjewel$'
      start_period: 10s
      start_interval: 2s
      interval: 5m
      timeout: 1s
      retries: 1
    memswap_limit: 99G
  docker-socket-proxy:
    cpu_shares: 256
    environment:
      CONTAINERS: '1'
      EVENTS: '1'
      INFO: '1'
      PING: '1'
      POST: '0' # Allow only GET and HEAD requests.
      VERSION: '1'
    expose:
      - '2375'
    healthcheck:
      test:
        ['CMD', 'wget', '--spider', '--quiet', 'http://localhost:2375/_ping']
      start_period: 10s
      start_interval: 1s
      interval: 5m
      timeout: 1s
      retries: 1
    image: ghcr.io/tecnativa/docker-socket-proxy:v0.4.2@sha256:1f3a6f303320723d199d2316a3e82b2e2685d86c275d5e3deeaf182573b47476
    networks:
      - docker-socket-proxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
  grafana:
    cpu_shares: 512
    depends_on:
      - loki
      - prometheus
    env_file:
      - .env.grafana.local
    environment:
      GF_PLUGINS_PREINSTALL_SYNC: grafana-lokiexplore-app@2.4.0
    expose:
      - '3000'
    image: grafana/grafana:13.1.3@sha256:ab5cb380e3ff3172d6c8bd2e7cfd31cce977d2881b260e1f5bc089bf0b759b43
    networks:
      - external # Allows Grafana to download plugins.
      - internal
    volumes:
      - grafana-data:/var/lib/grafana
  initialize_database:
    <<: *default-rails-config
    cpu_shares: 256
    depends_on:
      postgres:
        condition: service_healthy
      redis-app:
        condition: service_healthy
      redis-cache:
        condition: service_healthy
      vector:
        condition: service_started
  loki:
    cpu_shares: 512
    image: grafana/loki:3.7.6@sha256:efd47c67f9bac88ca29bcf8cb997d9ab29d1848bd0aff579282295542a745952
    command:
      - -config.file=/etc/loki/local-config.yaml
      - -log.level=warn
    expose:
      - '3100'
    logging: *default-logging
    networks:
      - internal
    volumes:
      - loki-data:/loki
  nginx:
    cpu_shares: 4096
    depends_on:
      vector:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 10M
    entrypoint: '/bin/sh -c ''while :; do sleep 6h & wait $${!}; nginx -s reload; done & /docker-entrypoint.sh nginx -g "daemon off;"'''
    env_file:
      - .env.nginx.local
    healthcheck:
      test: |-
        curl -s -o /dev/null -w "%{http_code}" --header 'Host: davidrunger.com' http://localhost/nginx-health | grep -q "^200$" || false
      start_period: 60s
      start_interval: 2s
      interval: 5m
      timeout: 3s
      retries: 1
    image: nginx:1.31.3-alpine@sha256:4a73073bd557c65b759505da037898b61f1be6cbcc3c2c3aeac22d2a470c1752
    logging: *default-logging
    memswap_limit: 99G
    networks:
      - external
      - internal
    ports:
      - 80:80
      - 443:443
    profiles:
      - nondefault
    volumes:
      - ./config/nginx/:/etc/nginx/
      - ./ssl-data/certbot/conf:/etc/letsencrypt
      - ./ssl-data/certbot/www:/var/www/_letsencrypt
      - app-public:/var/www/david-runger-public:ro
  node_exporter:
    cpu_shares: 512
    expose:
      - '9100'
    image: prom/node-exporter:v1.12.1@sha256:1b4e4438faca4dd7e001dd445d161a4a2091b0fededa84093b3a8dfeae1f1be0
    networks:
      - internal
  postgres:
    command:
      - postgres
      - -c
      - shared_preload_libraries=pg_stat_statements
      - -c
      - pg_stat_statements.track=all
      - -c
      - pg_stat_statements.max=10000
      - -c
      - track_activity_query_size=2048
    cpu_shares: 2048
    depends_on:
      vector:
        condition: service_started
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 50M
    env_file:
      - .env.postgres.local
    environment:
      POSTGRES_INITDB_ARGS: --auth=scram-sha-256
      POSTGRES_USER: david_runger
    healthcheck:
      test: ['CMD', 'pg_isready', '-U', 'david_runger']
      start_period: 20s
      start_interval: 1s
      interval: 5m
      timeout: 1s
      retries: 1
    image: postgres:18.6-alpine@sha256:432b3b824c0769275ec9b0947736ef8b376d6997bcaa9de29818f613819c2feb
    logging: *default-logging
    memswap_limit: 99G
    networks:
      - internal
    volumes:
      - postgres-data-v18:/var/lib/postgresql
  prometheus:
    cpu_shares: 512
    expose:
      - '9090'
    image: prom/prometheus:v3.13.2@sha256:508729e0e2d18e11fd742a5a5ca70e557b940a93948c3c95fd0123a6fd538b69
    networks:
      - internal
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus-data:/prometheus
  rails_metrics:
    <<: *default-rails-config
    cpu_shares: 512
    entrypoint: bin/prometheus_exporter --bind 0.0.0.0
    expose:
      - '9394'
    networks:
      - internal
  redis-app:
    <<: *redis
    # https://stackoverflow.com/a/72593084/4009384
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD is required}"
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 12M
    env_file:
      - .env.redis-app.local
    memswap_limit: 99G
    volumes:
      - redis:/data
  redis-cache:
    <<: *redis
    # https://stackoverflow.com/a/72593084/4009384
    command:
      - /bin/sh
      - -c
      # - Double dollars, so that the variable is not expanded by Docker Compose
      # - Surround by quotes, so that the shell does not split the password
      # - The ${variable:?message} syntax causes shell to exit with a non-zero
      #   code and print a message, when the variable is not set or empty
      - redis-server /usr/local/etc/redis/redis.conf --requirepass "$${REDIS_PASSWORD:?REDIS_PASSWORD is required}"
    cpu_shares: 2048
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 6M
    env_file:
      - .env.redis-cache.local
    memswap_limit: 99G
    volumes:
      - ./redis/redis-cache.conf:/usr/local/etc/redis/redis.conf
  redis-overcommit:
    build: https://raw.githubusercontent.com/bkuhl/redis-overcommit-on-host/09215f160d59a7289ab3f4734f235659cdb8d269/Dockerfile
    cpu_shares: 256
    restart: 'no'
    volumes:
      - /proc/sys/vm:/mnt/vm
  s3_db_backup:
    cpu_shares: 256
    depends_on:
      vector:
        condition: service_started
    env_file:
      - .env.s3_db_backup.local
    image: dokku/s3backup:0.18.2@sha256:a781df6117de0ecfebdc2d67643a576ebea84c0bdddf9bd8686e515e05cde649
    logging: *default-logging
    networks:
      - external
    profiles:
      - nondefault
  vector:
    command:
      - '--config'
      - '/etc/vector/vector.yaml'
      - '--require-healthy'
      - 'true'
      - '--watch-config'
    cpu_shares: 512
    depends_on:
      docker-socket-proxy:
        condition: service_healthy
    image: timberio/vector:0.57.0-alpine@sha256:19e3526faf4d4b1ed0c28a0d68d4cc3a1e13e437099986a5b7a768707907497c
    networks:
      - docker-socket-proxy
      - internal
    volumes:
      - ./vector/vector.yaml:/etc/vector/vector.yaml:ro
  web:
    <<: *default-rails-config
    command: ['bin/rails', 'server', '--binding', '0.0.0.0']
    cpu_shares: 4096
    deploy:
      resources:
        limits:
          memory: 99G
        reservations:
          memory: 230M
    environment:
      RAILS_MAX_THREADS: 2
    expose:
      - '3000'
    healthcheck:
      test: curl --silent --output /dev/null --fail localhost:3000/up
      start_period: 60s
      start_interval: 2s
      interval: 5m
      timeout: 5s
      retries: 1
    memswap_limit: 99G
    profiles:
      - nondefault
    volumes:
      - ./blog:/app/blog:ro
  worker:
    <<: *default-rails-config
    command: ['bin/sidekiq']
    cpu_shares: 1024
    deploy:
      resources:
        reservations:
          memory: 36M
    healthcheck:
      test: REDIS_URL="$$REDIS_URL/1" bin/sidekiqmon | grep --quiet "$$(hostname)"
      start_period: 60s
      start_interval: 10s
      interval: 5m
      timeout: 10s
      retries: 1

networks:
  docker-socket-proxy:
    driver: bridge
    internal: true
  external:
    driver: bridge
  internal:
    driver: bridge
    internal: true

volumes:
  app-public:
  grafana-data:
  loki-data:
  postgres-data-v18:
  prometheus-data:
  redis:
