---
version: '3.8'

services:
  postgres:
    image: postgres:15.1-alpine
    volumes:
      - postgresql:/var/lib/postgresql/data:delegated
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: david_runger
      POSTGRES_HOST_AUTH_METHOD: trust
  redis:
    image: redis:7.0.7-alpine
    ports:
      - '6379:6379'
    command: redis-server
    volumes:
      - redis:/data:delegated

volumes:
  postgresql:
  redis:
