minimumReleaseAge: 7200 # Wait 5 days before installing new releases.
strictDepBuilds: true
allowBuilds:
  '@percy/core': true
  '@tailwindcss/oxide': true
  esbuild: true
  unrs-resolver: true
  vue-demi: true
  '@parcel/watcher': false
minimumReleaseAgeExclude:
  - dompurify@3.4.11
  - undici@7.28.0
