// This is a generated file. Do not edit this file directly.

export interface BlogShowBootstrap {
    current_user?: CurrentUser | null;
    nonce:         string;
}

interface CurrentUser {
    gravatar_url: null | string;
    id:           number;
    public_name:  null | string;
}
