// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Root",
  "definitions": {
    "Root": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "nonce": {
          "type": "string",
          "format": "uuid"
        },
        "current_user": {
          "$ref": "#/definitions/CurrentUser"
        },
        "spouse": {
          "anyOf": [
            {
              "$ref": "#/definitions/CurrentUser"
            },
            {
              "type": "null"
            }
          ]
        },
        "own_stores": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Store"
          }
        },
        "spouse_stores": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Store"
          }
        }
      },
      "required": [
        "current_user",
        "nonce",
        "own_stores",
        "spouse",
        "spouse_stores"
      ],
      "title": "Root"
    },
    "CurrentUser": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        }
      },
      "required": ["email", "id"],
      "title": "CurrentUser"
    },
    "Store": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "notes": {
          "anyOf": [
            {
              "type": "null"
            },
            {
              "type": "string"
            }
          ]
        },
        "own_store": {
          "type": "boolean"
        },
        "private": {
          "type": "boolean"
        },
        "viewed_at": {
          "anyOf": [
            {
              "type": "string",
              "format": "date-time"
            },
            {
              "type": "null"
            }
          ]
        },
        "items": {
          "type": "array",
          "items": {
            "$ref": "#/definitions/Item"
          }
        }
      },
      "required": [
        "id",
        "items",
        "name",
        "notes",
        "own_store",
        "private",
        "viewed_at"
      ],
      "title": "Store"
    },
    "Item": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "name": {
          "type": "string"
        },
        "needed": {
          "type": "integer"
        },
        "store_id": {
          "type": "integer"
        }
      },
      "required": ["id", "name", "needed", "store_id"],
      "title": "Item"
    }
  }
} as const;

export type GroceriesIndexBootstrap = FromSchema<typeof schema>;
