// This is a generated file. Do not edit this file directly.

export interface GroceriesIndexBootstrap {
    alert_toast_messages?:  string[];
    current_user:           CurrentUser;
    nonce:                  string;
    notice_toast_messages?: string[];
    own_stores:             Store[];
    spouse:                 CurrentUser | null;
    spouse_stores:          Store[];
}

interface CurrentUser {
    email: string;
    id:    number;
}

interface Store {
    id:        number;
    items:     Item[];
    name:      string;
    notes:     null | string;
    own_store: boolean;
    private:   boolean;
    viewed_at: string | null;
}

interface Item {
    id:       number;
    name:     string;
    needed:   number;
    store_id: number;
}
