// This is a generated file. Do not edit this file directly.

export interface ModelGraphIndexBootstrap {
    model_metadata: ModelMetadatum[];
    nonce:          string;
}

interface ModelMetadatum {
    associations: Association[];
    columns:      Column[];
    model_name:   string;
    table_name:   string;
}

interface Association {
    class_name: string;
    macro:      Macro;
    name:       string;
    options:    Options;
}

export enum Macro {
    BelongsTo = "belongs_to",
    HasMany = "has_many",
    HasOne = "has_one",
}

interface Options {
    as?:             As;
    autosave?:       boolean;
    class_name?:     string;
    dependent?:      boolean | DependentEnum;
    extend?:         string[];
    foreign_key?:    string;
    inverse_of?:     boolean | string;
    optional?:       boolean;
    polymorphic?:    boolean;
    source?:         string;
    strict_loading?: boolean;
    through?:        string;
    touch?:          boolean;
}

export enum As {
    Item = "item",
    LogEntryDatum = "log_entry_datum",
    Record = "record",
}

export enum DependentEnum {
    Destroy = "destroy",
    Nullify = "nullify",
    RestrictWithException = "restrict_with_exception",
}

interface Column {
    default: null | string;
    name:    string;
    null:    boolean;
    type:    Type;
}

export enum Type {
    Boolean = "boolean",
    Datetime = "datetime",
    Float = "float",
    Integer = "integer",
    Jsonb = "jsonb",
    String = "string",
    Text = "text",
}
