// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Root",
  "definitions": {
    "Root": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "nonce": {
          "type": "string",
          "format": "uuid"
        },
        "current_user": {
          "$ref": "#/definitions/CurrentUser"
        },
        "quiz": {
          "$ref": "#/definitions/Quiz"
        }
      },
      "required": ["current_user", "nonce", "quiz"],
      "title": "Root"
    },
    "CurrentUser": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "email": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        }
      },
      "required": ["email", "id"],
      "title": "CurrentUser"
    },
    "Quiz": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "owner_id": {
          "type": "integer"
        },
        "hashid": {
          "type": "string"
        }
      },
      "required": ["hashid", "owner_id"],
      "title": "Quiz"
    }
  }
} as const;

export type QuizShowBootstrap = FromSchema<typeof schema>;
