default: &default
  adapter: redis

development:
  <<: *default
  channel_prefix: david_runger_development
  url: <%= ENV.fetch('REDIS_URL', 'redis://localhost:6379') %>

test:
  <<: *default
  channel_prefix: david_runger_test
  url: redis://localhost:6379

production:
  <<: *default
  channel_prefix: david_runger_production
  url: <%= ENV.fetch('REDIS_URL', nil) %>
