default: &default
  adapter: redis

development:
  <<: *default
  channel_prefix: david_runger_development
  url: redis://localhost:6379

test:
  <<: *default
  channel_prefix: david_runger_test
  url: redis://localhost:6379

production:
  <<: *default
  channel_prefix: david_runger_production
  ssl_params:
    verify_mode: <%= OpenSSL::SSL::VERIFY_NONE %>
  # We'll check ENV['REDIS_TLS_URL'] for Heroku review apps, which can't decrypt credentials
  url: <%= RedisOptions.production_redis_url %>
