config:
  app_redis_db: 0
  sidekiq_redis_db: 1

jobs:
  DataMonitors::Launcher: '**:07' # hourly at 7 minutes after
  SendLogReminderEmails: '**:**' # every minute
  TruncateTables: '04:58' # daily at 4:58am UTC
  CheckHomeLinks::Launcher: '07:36' # daily at 7:36am UTC
