config:
  app_redis_db: 0
  sidekiq_redis_db: 1
  time_zone: America/Chicago

jobs:
  DataMonitors::Launcher: '**:07' # hourly at 7 minutes after
  SendLogReminderEmails: '**:**' # every minute
  PgHero::CaptureQueryStats: '**:%5+3' # every 5 minutes with an offset of 3 (3, 8, 13, ...)
  PgHero::CaptureSpaceStats: '22:52' # daily at 10:52pm Central Time
  PgHero::CleanQueryStats: '23:02' # daily at 11:02pm Central Time
  # Avoid 2:32am - 3:56am Central Time (plus padding) because we do restarts then.
  TruncateTables: '01:58' # daily at 1:58am Central Time
  CheckLinks::LaunchPageFetches: '04:16' # daily at 4:16am Central Time
