config:
  app_redis_db: 0
  sidekiq_redis_db: 1
  time_zone: America/Chicago

jobs:
  DataMonitors::Launcher: '**:07' # hourly at 7 minutes after
  CheckWebsite: '**:30' # hourly at 30 minutes after
  SendLogReminderEmails: '**:**' # every minute
  # Avoid 2:32am - 3:56am Central Time (plus padding) because we do restarts then.
  TruncateTables: '01:58' # daily at 1:58am Central Time
  CheckHomeLinks::Launcher: '04:16' # daily at 4:16am Central Time
