# Note: You must restart bin/webpack-dev-server for changes to take effect

default: &default
  source_path: app/javascript
  source_entry_path: packs
  public_output_path: packs
  cache_path: tmp/cache/webpacker
  check_yarn_integrity: false

  # Additional paths webpack should lookup modules
  # ['app/assets', 'engine/foo/app/assets']
  resolved_paths: []

  # Reload manifest.json on all requests so we reload latest compiled packs
  cache_manifest: false

  extensions:
    - .js
    - .jsx
    - .vue
    - .scss
    - .css
    - .png
    - .svg
    - .gif
    - .jpeg
    - .jpg

development:
  <<: *default
  compile: true
  check_yarn_integrity: true

  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    pretty: false
    https: false
    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    # Inline should be set to true if using HMR
    inline: true
    overlay: true
    disable_host_check: true
    use_local_ip: false

test:
  <<: *default
  cache_manifest: true
  source_entry_path: packs
  public_output_path: packs-test
  compile: false
  hmr: false
  extract_css: true
  # Reference: https://webpack.js.org/configuration/dev-server/
  dev_server:
    pretty: false
    https: false
    host: localhost
    port: 8080
    public: localhost:8080
    hmr: false
    # Inline should be set to true if using HMR
    inline: false
    overlay: true
    disable_host_check: true
    use_local_ip: false

production:
  <<: *default
  # Cache manifest.json for performance
  cache_manifest: true
  # Production depends on precompilation of packs prior to booting for performance.
  compile: false
  # Tell Rails we want to serve compiled/extracted CSS files from public/packs/
  extract_css: true
