inherit_from:
  - ../.rubocop.yml
Lint/AmbiguousBlockAssociation:
  Enabled: false
Performance/ChainArrayAllocation:
  Enabled: false
RSpec/ExampleLength:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
Style/IpAddresses:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - describe
    - include
    - not_to
    - require
    - require_relative
    - to
Style/Send:
  Enabled: false
