inherit_from:
  - ../../.rubocop.yml
Metrics/MethodLength:
  Enabled: false
Style/MethodCallWithArgsParentheses:
  IgnoredMethods:
    - add_foreign_key
    - add_column
    - add_index
    - belongs_to
    - bigint
    - change
    - change_column
    - change_column_null
    - create_table
    - datetime
    - desc
    - describe
    - drop_table
    - gem
    - fail
    - file
    - float
    - foreign_key
    - head
    - include
    - index
    - integer
    - jsonb
    - load
    - not_to
    - p
    - print
    - puts
    - references
    - remove_column
    - remove_index
    - render
    - require
    - ruby
    - run
    - string
    - source
    - text
    - timestamp
    - to
Style/StringLiterals:
  Enabled: false
