export type CommentsIndexResponse = Array<CommentsIndexResponseElement>

// This is a generated file. Do not edit this file directly.

interface CommentsIndexResponseElement {
    content:    string;
    created_at: string;
    id:         number;
    parent_id:  number | null;
    user:       User | null;
}

interface User {
    gravatar_url: null | string;
    id:           number;
    public_name:  null | string;
}
