// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Root",
  "definitions": {
    "Root": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "content": {
          "type": "string"
        },
        "created_at": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "parent_id": {
          "type": ["integer", "null"]
        },
        "user": {
          "$ref": "#/definitions/User"
        }
      },
      "required": ["content", "created_at", "id", "parent_id", "user"],
      "title": "Root"
    },
    "User": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "id": {
          "type": "integer"
        },
        "public_name": {
          "type": "string"
        },
        "gravatar_url": {
          "type": "string",
          "format": "uri",
          "qt-uri-protocols": ["https"]
        }
      },
      "required": ["gravatar_url", "id", "public_name"],
      "title": "User"
    }
  }
} as const;

export type CommentCreateResponse = FromSchema<typeof schema>;
