// This is a generated file. Do not edit this file directly.

export interface DeletedItemRestorationCreateResponse {
    id:        number;
    name:      string;
    needed:    number;
    store_ids: number[];
}
