// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "type": "object",
  "additionalProperties": false,
  "properties": {
    "restore_item_path": {
      "type": "string"
    }
  },
  "required": ["restore_item_path"]
} as const;

export type ItemDestroyResponse = FromSchema<typeof schema>;
