// This file was generated by quicktype. Do not edit this file directly.

export interface ItemCreateResponse {
    id:        number;
    name:      string;
    needed:    number;
    store_ids: number[];
}
