// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "type": "object",
  "properties": {
    "created_at": {
      "type": "string",
      "pattern": "^[0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}Z$"
    },
    "data": { "type": ["number", "string"] },
    "id": { "type": "integer" },
    "log_id": { "type": "integer" },
    "note": { "type": ["string", "null"] }
  }
} as const;

export type LogEntryShowResponse = FromSchema<typeof schema>;
