export type LogEntriesIndexResponse = Array<LogEntriesIndexResponseElement>

// This file was generated by quicktype. Do not edit this file directly.

interface LogEntriesIndexResponseElement {
    created_at: string;
    data:       number | string;
    id:         number;
    log_id:     number;
    note:       null | string;
}
