// This file was generated by quicktype. Do not edit this file directly.

export interface LogUpdateResponse {
    data_label:                             string;
    data_type:                              string;
    description:                            null | string;
    email_submission_token_last_rotated_at: null | string;
    id:                                     number;
    log_shares:                             User[];
    name:                                   string;
    publicly_viewable:                      boolean;
    reminder_time_in_seconds:               number | null;
    slug:                                   string;
    user:                                   User;
}

interface User {
    email: string;
    id:    number;
}
