// This file was generated by quicktype. Do not edit this file directly.

export interface MyAccountUpdateResponse {
    gravatar_url: null | string;
    id:           number;
    public_name:  null | string;
}
