// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "type": "object",
  "properties": {
    "id": { "type": "integer" },
    "score": { "type": "integer" },
    "emotional_need": {
      "type": "object",
      "properties": {
        "description": { "type": "string" },
        "id": { "type": "number" },
        "name": { "type": "string" }
      },
      "additionalProperties": false
    }
  },
  "additionalProperties": false
} as const;

export type NeedSatisfactionRatingShowResponse = FromSchema<typeof schema>;
