// This file was generated by quicktype. Do not edit this file directly.

export interface StoreCreateResponse {
    id:        number;
    items:     Item[];
    name:      string;
    notes:     null | string;
    own_store: boolean;
    private:   boolean;
    viewed_at: string;
}

interface Item {
    id:        number;
    name:      string;
    needed:    number;
    store_ids: number[];
}
