// This file was generated by quicktype. Do not edit this file directly.

export interface StoreSectionSchemesIndexResponse {
    store_section_schemes: StoreSectionScheme[];
}

interface StoreSectionScheme {
    id:             number;
    name:           string;
    store_sections: StoreSection[];
}

interface StoreSection {
    id:   number;
    name: string;
}
