// This file was generated by quicktype. Do not edit this file directly.

export interface StoreUpdateResponse {
    id:                       number;
    item_section_assignments: ItemSectionAssignment[];
    items:                    Item[];
    name:                     string;
    notes:                    null | string;
    own_store:                boolean;
    private:                  boolean;
    section_configuration:    StoreSectionConfiguration | null;
    viewed_at:                string;
}

interface ItemSectionAssignment {
    item_id:          number;
    store_section_id: number;
}

interface Item {
    id:        number;
    name:      string;
    needed:    number;
    store_ids: number[];
}

interface StoreSectionConfiguration {
    sectioning_enabled:   boolean;
    store_section_scheme: StoreSectionScheme | null;
}

interface StoreSectionScheme {
    id:             number;
    name:           string;
    store_sections: StoreSection[];
}

interface StoreSection {
    id:   number;
    name: string;
}
