// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "type": "object",
  "properties": {
    "created_at": { "type": "string" },
    "id": { "type": "integer" },
    "publicly_viewable": { "type": "boolean" },
    "rep_totals": { "type": "object" },
    "time_in_seconds": { "type": "integer" },
    "username": { "type": "string" }
  }
} as const;

export type WorkoutShowResponse = FromSchema<typeof schema>;
