// This is a generated file. Do not edit this file directly.

import { FromSchema } from 'json-schema-to-ts';

const schema = {
  "$schema": "http://json-schema.org/draft-06/schema#",
  "$ref": "#/definitions/Root",
  "definitions": {
    "Root": {
      "type": "object",
      "additionalProperties": false,
      "properties": {
        "created_at": {
          "type": "string"
        },
        "id": {
          "type": "integer"
        },
        "publicly_viewable": {
          "type": "boolean"
        },
        "time_in_seconds": {
          "type": "integer"
        },
        "rep_totals": {
          "$ref": "#/definitions/RepTotals"
        },
        "username": {
          "type": "string"
        }
      },
      "required": [
        "created_at",
        "id",
        "publicly_viewable",
        "rep_totals",
        "time_in_seconds",
        "username"
      ],
      "title": "Root"
    },
    "RepTotals": {
      "type": "object",
      "title": "RepTotals"
    }
  }
} as const;

export type WorkoutCreateResponse = FromSchema<typeof schema>;
