// This file was generated by quicktype. Do not edit this file directly.

export interface WorkoutUpdateResponse {
    created_at:        string;
    id:                number;
    publicly_viewable: boolean;
    rep_totals:        { [key: string]: unknown };
    time_in_seconds:   number;
    username:          string;
}
