// Typelizer digest a12eb14f3e1ba4b8e1fc351dc639664e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type CheckIn = {
  id: number;
  submitted: boolean;
}

export default CheckIn;
