// Typelizer digest e831e569aa5b80aef098870cdacaa2f9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type CheckIn = {
  id: number;
  submitted: boolean;
}

export default CheckIn;
