// Typelizer digest 49099459b2073e9c63349025f2986fbc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserSerializerPublic} from '@/types'

type Comment = {
  content: string;
  created_at: string;
  id: number;
  parent_id: number | null;
  user: UserSerializerPublic | null;
}

export default Comment;
