// Typelizer digest 8b21309548e115f3e8087841336979fc
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserSerializerPublic} from '@/types'

type Comment = {
  content: string;
  created_at: string;
  id: number;
  parent_id: number | null;
  user: UserSerializerPublic;
}

export default Comment;
