// Typelizer digest 84ea18cbb494328dbe19afd44a66c43a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserSerializerPublic} from '@/types'

type Comment = {
  content: string;
  id: number;
  parent_id: number | null;
  created_at: string;
  user: UserSerializerPublic | null;
}

export default Comment;
