// Typelizer digest d80443027a992315580ea1c6fc425ccf
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type EmotionalNeed = {
  description: string | null;
  id: number;
  name: string;
}

export default EmotionalNeed;
