// Typelizer digest 19f516beb8d884f7016fb4451bfa647e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  needed: number;
  store_ids: Array<number>;
}

export default Item;
