// Typelizer digest e2df7826f98665c91c0790cc18f2bf49
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  needed: number;
  store_id: unknown;
}

export default Item;
