// Typelizer digest 80be1491235b738bbb036cba1a19d179
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type ItemSectionAssignment = {
  store_section_id: number;
  item_id: number;
}

export default ItemSectionAssignment;
