// Typelizer digest 18bcbf9c2a13578bed26b011180d95b7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Item = {
  id: number;
  name: string;
  needed: number;
  store_id: number;
}

export default Item;
