// Typelizer digest 1a988ed301d4ac18b29585ad2a6a70a9
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserSerializerBasic, LogShare} from '@/types'

type Log = {
  data_label: string;
  data_type: string;
  description: string | null;
  id: number;
  name: string;
  slug: string;
  publicly_viewable?: boolean;
  email_submission_token_last_rotated_at?: string | null;
  reminder_time_in_seconds?: number | null;
  user: UserSerializerBasic;
  log_shares?: Array<LogShare>;
}

export default Log;
