// Typelizer digest e57df484f35ba79fa1dcd37577f4d1ef
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {UserSerializerBasic, LogShare} from '@/types'

type Log = {
  data_label: string;
  data_type: string;
  description: string | null;
  id: number;
  name: string;
  slug: string;
  publicly_viewable?: boolean;
  reminder_time_in_seconds?: number | null;
  user: UserSerializerBasic;
  log_shares?: Array<LogShare>;
}

export default Log;
