// Typelizer digest 4b4adb2fda3e333febc77c18b204858a
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {LogEntryDataValue} from '@/types'

type LogEntry = {
  id: number;
  log_id: number;
  note: string | null;
  created_at: string;
  data: LogEntryDataValue;
}

export default LogEntry;
