// Typelizer digest 6bd87ab1f61e5946df812941a23ab398
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type LogShare = {
  email: string;
  id: number;
}

export default LogShare;
