// Typelizer digest 25b83b2a64536c36f2cc827df6d96316
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {EmotionalNeed} from '@/types'

type NeedSatisfactionRating = {
  id: number;
  score: number | null;
  emotional_need: EmotionalNeed;
}

export default NeedSatisfactionRating;
