// Typelizer digest 110b4f9f345137152e846934a5212b84
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Quiz = {
  owner_id: number;
  hashid: string;
}

export default Quiz;
