// Typelizer digest eccb35d4cb36e5970a3043a472857d1e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Quiz = {
  owner_id: number;
  hashid: string;
}

export default Quiz;
