// Typelizer digest 942cfd9e345176c7109f52c0364c21d6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Item} from '@/types'

type Store = {
  id: number;
  name: string;
  notes: string | null;
  private: boolean;
  items: Array<Item>;
  own_store: boolean;
  viewed_at: string | null;
}

export default Store;
