// Typelizer digest 2a0fdf2f2c23fa14a7006f253c70d2c6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {StoreSection} from '@/types'

type StoreSectionScheme = {
  id: number;
  name: string;
  store_sections: Array<StoreSection>;
}

export default StoreSectionScheme;
