// Typelizer digest a0b3dcb28b75177a68344b892222833d
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {StoreSectionScheme} from '@/types'

type StoreSectionConfiguration = {
  sectioning_enabled: boolean;
  store_section_scheme: StoreSectionScheme | null;
}

export default StoreSectionConfiguration;
