// Typelizer digest 19f5f81208aa3bef3f909ccb304cfb2e
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {Item} from '@/types'

type Store = {
  id: number;
  name: string;
  notes: string | null;
  own_store: boolean;
  private: boolean;
  viewed_at: string | null;
  items: Array<Item>;
}

export default Store;
