// Typelizer digest b2c42c030a5139eb1c28a020d84b06b7
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {StoreSectionConfiguration, ItemSectionAssignment, Item} from '@/types'

type Store = {
  id: number;
  name: string;
  notes: string | null;
  private: boolean;
  items: Array<Item>;
  own_store: boolean;
  viewed_at: string | null;
  section_configuration: StoreSectionConfiguration | null;
  item_section_assignments: Array<ItemSectionAssignment>;
}

export default Store;
