// Typelizer digest 3e8df250eaf5be976bd5333c78b75d25
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type StoreSection = {
  id: number;
  name: string;
}

export default StoreSection;
