// Typelizer digest 106adfdb6325e56a401a9771795f8c34
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {EmojiDataWithBoostedName} from '@/types'

type UserSerializerWithEmojiBoosts = {
  email: string;
  id: number;
  emoji_boosts: Array<EmojiDataWithBoostedName>;
}

export default UserSerializerWithEmojiBoosts;
