// Typelizer digest 6bab0801cc3a5d5dfedb572e06d87d1c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type UserSerializerPublic = {
  id: number;
  public_name: string | null;
  gravatar_url: string | null;
}

export default UserSerializerPublic;
