// Typelizer digest 473afdf2c5d830f5ef4f8e10bdef1609
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {WorkoutPlan} from '@/types'

type UserSerializerWithDefaultWorkout = {
  email: string;
  id: number;
  default_workout: WorkoutPlan;
}

export default UserSerializerWithDefaultWorkout;
