// Typelizer digest 7640a7a2ec4f5ffccd047c435c76ccf8
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type UserSerializerPublic = {
  id: number;
  public_name: string;
  gravatar_url: string;
}

export default UserSerializerPublic;
