// Typelizer digest 4175396f5ed3fcf21bf5b619c1826232
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type UserSerializerBasic = {
  email: string;
  id: number;
}

export default UserSerializerBasic;
