// Typelizer digest 35f19f4ce3fe5c7f37eedb1106527c3c
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {WorkoutPlan} from '@/types'

type UserSerializerWithDefaultWorkout = {
  email: string;
  id: number;
  default_workout: WorkoutPlan;
}

export default UserSerializerWithDefaultWorkout;
