// Typelizer digest cb8d055d0e4c4ba1b44ced0d0167ac1b
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type UserSerializerPublic = {
  id: number;
  public_name: string;
  gravatar_url: string;
}

export default UserSerializerPublic;
