// Typelizer digest 281dc9df6c62d867b2ef45ba4ef95438
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {EmojiDataWithBoostedName} from '@/types'

type UserSerializerWithEmojiBoosts = {
  email: string;
  id: number;
  emoji_boosts: Array<EmojiDataWithBoostedName>;
}

export default UserSerializerWithEmojiBoosts;
