// Typelizer digest 82285395f1a8de94fd66c059f7f60ec6
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type {RepTotals} from '@/types'

type Workout = {
  created_at: string;
  id: number;
  publicly_viewable: boolean;
  time_in_seconds: number;
  rep_totals: RepTotals;
  username: string;
}

export default Workout;
